name: Publish AaC Python Package to PyPI

on:
  release:
    types: [published]

defaults:
  run:
    working-directory: ./python

jobs:
  build_deployment_artifacts:
    name: Build Artifacts
    uses: ./.github/workflows/python-build-artifacts.yml

  deploy_artifacts:
    name: Deploy Artifacts
    runs-on: ubuntu-latest
    needs: build_deployment_artifacts
    steps:
      - name: Download Python Wheel
        uses: actions/download-artifact@v2
        with:
          name: aac_wheel
          path: python/dist/

      - name: Publish distribution to PyPI
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_DEPLOY_TOKEN }}
          packages_dir: python/dist/